Added test, fixed bugs for Integrations
hiqdev/hipanel-module-integrations pull request #7
Opened 2019-04-23 09:51 UTC by tafid

2019-04-23 09:53 UTC, hiqsol approved these changes

2019-04-23 09:56 UTC, MaksimGayduk commented on tests/acceptance/seller/IntegrationsCest.php
> +
лучше использовать константы класса
`
const PROVIDER_TYPE_DOMAIN = 'domain';
`

2019-04-26 10:37 UTC, SilverFire requested changes

2019-04-26 10:37 UTC, SilverFire commented on tests/acceptance/seller/IntegrationsCest.php
> +        foreach ($this->getVariants() as $providerType => $providerName) {
Замени на https://codeception.com/docs/07-AdvancedUsage#DataProvider-Annotations

2019-04-26 10:37 UTC, SilverFire commented on tests/acceptance/seller/IntegrationsCest.php
> +        $I->dontSeeElement("//*[contains(@class, 'has-error')]");
```suggestion
        $createFirstItemPage->hasNotErrors();
```

2019-04-26 10:37 UTC, SilverFire commented on tests/acceptance/seller/IntegrationsCest.php
> +            $I->dontSeeElement("//*[contains(@class, 'has-error')]");
```suggestion
            $updatePage->hasNotErrors();
```

2019-04-26 10:37 UTC, SilverFire commented on tests/acceptance/seller/IntegrationsCest.php
> +            $I->dontSeeElement("//*[contains(@class, 'has-error')]");
```suggestion
            $createPage->hasNotErrors();
```

2019-04-26 11:07 UTC, hiqsol approved these changes

2019-04-26 14:58 UTC, SilverFire approved these changes

2019-04-26 14:58 UTC, SilverFire commented
Отличная работа!

2019-04-26 14:58 UTC, merged